cloud:
  aws:
    credentials:
      access-key: 9999999999999999999999999
      secret-key: 88888888888888888888888888888
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: 0000000000000000000


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8292

